version: '3'
services:
  microservice:
    build:
      context: ./microservice
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - mynetwork

  api-gateway:
    build:
      context: ./apigateway
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    depends_on:
      - microservice
    networks:
      - mynetwork

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork

volumes:
  mongo-data:

networks:
  mynetwork:
    driver: bridge
